services:
  - type: web
    name: rochester-backend
    env: java
    buildCommand: ./mvnw package
    startCommand: java -jar target/*.jar
    plan: free
    branch: main
    buildFilter:
      paths:
        - '**/*'
    autoDeploy: true
    build:
  environment:
    JAVA_HOME: /opt/render/project/.jdk
  buildCommand: ./mvnw package

